### ISSUE TITLE
Resync with upstream v16.1?

### ISSUE THREAD

**Issue by ShaheedHaque** [jaraco/calendra#21]
Is there a plan to release something synced to up[stream v16.1.0 (2021-10-01)? I am specifically interested in the UK holiday changes please...

**Comment by jaraco** [comment]
I'm in favor. Last sync was 14.1. It'll take some work to get these changes integrated.

**Comment by jaraco** [comment]
Tonight, I synced up main to workalendar 14.3.0. There are still some tests failing (mainly China, which was fixed in workalendar 16.2), but the code is more in sync so subsequent changes should be easier to adopt.

**Comment by jaraco** [comment]
In 7fba0cb, I've pushed a sync with workalendar 16.3, but there's a problem. A test for a new calendar (kazakhstan) is failing because "Nauryz Meyramy" is appearing multiple times on the same day (triggering a failure in the ical export). @ShaheedHaque Can you investigate and determine a proper fix for supporting Kazakhstan with the SeriesShiftMixin and IslamicMixin?

**Comment by jaraco** [comment]
Fixed in 25399ce (v7.5.0).
