### ISSUE TITLE
UK change to 2020 early May bank holiday

### ISSUE THREAD

**Issue by ShaheedHaque** [jaraco/calendra#8]
The UK early May bank holiday for 2020 is changing from the expected date to 8-May:

- [Official record from UK government site](https://www.gov.uk/bank-holidays)
- [Background info from BBC](https://www.bbc.co.uk/news/uk-48565417)

I'd like to request this be added to Calendra please.

P.S. I've reviewed the contributing guidelines, and with a bit of advice to prevent breakage to what I guess is a high-usage calendar, I might be able to cook up a patch in due course if needed.

**Comment by jaraco** [comment]
Hi Shaheed. Thanks for the info.

Besides your reported concern, there are two additional concerns at play here:

- I don't have much time to spend on this project, so I'll only occasionally have time to keep the codebase in sync with the upstream changes. I won't be able to contribute new functionality or changes, but I am happy to review pull requests and cut releases.
- This issue probably should be first fixed upstream in the workalendar project. This fork seeks mainly to address the shortcomings of that project. This concern is exacerbated by the prior concern :/

**Comment by ShaheedHaque** [comment]
I was not previously clear on the relationship to upstream, but I now see a report there is the right first step. Thanks!

**Comment by ShaheedHaque** [comment]
Added [upstream issue](https://github.com/peopledoc/workalendar/issues/381) as suggested.

**Comment by ShaheedHaque** [comment]
FYI, upstream has released a [fix for this](https://github.com/peopledoc/workalendar/pull/384). Will you be able to do the sync or should I attempt one and do a PR?

**Comment by jaraco** [comment]
I'd be delighted if you would put together a PR, but I'd like it to include a merge of the master (or tagged release) following the patterns from previous syncs... which means you may run into conflicts and you may not be aware of the best resolution for those conflicts. Still, I'll have limited time to support this project, so to the extent that you can help support it, that would be most appreciated and I'm willing to spend whatever time it takes to help you with the process. Don't hesitate to let me know if you get stuck. Also, feel free (but not obliged) to document the process if it's not already (I don't think it is).

**Comment by ShaheedHaque** [comment]
OK. Here is what I see so far, please add/correct as needed:

1. On 5-Jan-2019, starting with a6bbc34e26, you merged workalendar v2.6.0 and workalendar/3.2.1.
1. Later that day, you tagged "3.0".

Now, upstream has changed quite a lot between v2.6.0 and v5.2.2 (the latest). Many of the changes are simple mechanical changes (e.g. code re-orgs) which can be applied easily, but there are also a lot of actual content changes. So, I roughly speaking, I need to:

1. Find the diffs between upstream v2.6.0 and v5.2.2.
1. Strip out the diffs for files we don't want to merge (largely, this is the files in the top level directory).
1. The remaining diffs are for files in directory "workalendar" in upstream, and "calendra" locally.
    - Apply the mechanical changes en-masse.
    - Apply the content changes with due care. It is not yet clear to me how much of this can be done using `git merge` versus careful `patch`ing.
1. Carefully record the procedure, and the tag to which we have synced.

Does that sound right? Any advice?

**Comment by jaraco** [comment]
Thanks for doing that analysis.

> Find the diffs between upstream v2.6.0 and v5.2.2.

Actually, as you observed, the 3.0 release of calendra includes changes from workalendar up through 3.2.1, so you only need to consider the changes from v3.2.1 to v5.2.2.

> It is not yet clear to me how much of this can be done using `git merge` versus careful patching.

I've always used (and recommend) `git merge`, so I don't omit any diffs and the full ancestry of every change is present. Git has been following the ancestry as well so is aware of the file renames (so changes in `workalendar/` get mapped to `calendra/` automatically).

But as you say, quite a lot has changed. One way I've found to manage the changes is to bite off in smaller chunks. For example, instead of merging v5.2.2, just merge for example v4.0.0, resolve any conflicts, verify tests run, and commit. Then repeat with another modest change until eventually you've merged v5.2.2.

At each merge, if the upstream has introduced any files that need not be included with calendra, then you should `git delete` them, but I'd only recommend that if the files are interfering with the package.

Note - you _will_ get merge conflicts for the changelog. You'll want to reformat the changes following the [previous pattern](https://calendra.readthedocs.io/en/latest/history.html), so that changes from upstream are indicated as such.

Feel free to give a `git merge d8be9de2aed8eed7e07d6e2a20f0fa511574f981` (workalendar/v4.0.0) a try and let me know how that goes.

**Comment by ShaheedHaque** [comment]
Thanks for the feedback. I considered the step-by-step approach, but in the end there was little to choose between it and just going all the way!

**Comment by jaraco** [comment]
A good way to ensure that know what changes to retain is use GitHub to look at the (presumed) intended differences were at the last merge. Here are the [differences after merging workalendar 3.2.1](https://github.com/jaraco/calendra/compare/1101b41347e6e80a07f35382cd2fd14b79912d4a...39e66d2894332cc544ade87085fbcdb5ae7be5e4).

**Comment by jaraco** [comment]
This issue is addressed with the latest merge. Big thanks for your patience on this matter. I hope the delayed experience hasn't sullied your interest in the project. I'd be delighted if you'd like to take a look at another sync with workalendar, if you're up for it. No obligation, though.

**Comment by ShaheedHaque** [comment]
I gave it a shot, as per the PR, but my system seems broken (even on
master) for tox in some way that I have not been able to diagnose. ANyway,
the diffs were pretty benign from what I could see, so perhaps you can take
a look when you have time.

Good luck...
